id: ance
title: 'ANCE'
description: |
    ANCE syncronise implementation

gpu: true
indexation:
    requirements: duration=2 days
    training_requirements: duration=4 days & cuda(mem=24G)
    indexspec: Flat

ance:
    optimization:
        steps_per_epoch: 128
        batch_size: 64
        max_epochs: 1200
        lr: 1.0e-5
        num_warmup_steps: 6000

    validation_interval: 8
    indexing_interval: 600
    sampling_interval: 600
    requirements: duration=5 days & cuda(mem=24G) * 2 & cpu(cores=40)

retrieval:
    requirements: duration=2 days & cuda(mem=24G)
    topK: 1000
    retTopK: 50
    batch_size_full_retriever: 200
    negative_sampler_topk: 200
