id: ance
title: 'ANCE'
description: |
    ANCE syncronise implementation

gpu: true
indexation:
    requirements: duration=4 days & cpu(cores=8)
    training_requirements: duration=4 days & cuda(mem=24G)
    indexspec: Flat

ance:
    optimization:
        steps_per_epoch: 100
        batch_size: 8
        max_epochs: 1000
        lr: 1.0e-6
        num_warmup_steps: 5000
        LAMB: true
        weight_decay: 0

    validation_interval: 10
    indexing_interval: 100
    sampling_interval: 100
    requirements: duration=5 days & cuda(mem=23G) * 2 & cpu(cores=8)

ance_warmup:
    optimization:
        batch_size: 32
        steps_per_epoch: 100
        max_epochs: 800
        lr: 2.0e-4
        num_warmup_steps: 1000
        LAMB: true
        weight_decay: 0

    validation_interval: 20
    requirements: duration=4 days & cuda(mem=23G) * 2

retrieval:
    requirements: duration=2 days & cuda(mem=24G)
    topK: 1000
    retTopK: 50
    batch_size_full_retriever: 200
    negative_sampler_topk: 10
    max_query: 65536
    trainTopK: 30
