id: splade_max
title: 'SPLADE_max: SPLADEv2 with max aggregation'
description: |
    SPLADE v2: Sparse Lexical and Expansion Model for Information Retrieval
    (Thibault Formal, Carlos Lassance, Benjamin Piwowarski, Stéphane Clinchant).
    2021. https://arxiv.org/abs/2109.10086

gpu: true
indexation:
    requirements: duration=2 days & cpu(mem=2G)
    training_requirements: duration=4 days & cuda(mem=24G)
    indexspec: Flat

splade:
    optimization:
        steps_per_epoch: 128
        batch_size: 96
        max_epochs: 1200
        lr: 1.0e-5
        num_warmup_steps: 6000

    validation_interval: 8
    indexing_interval: 128
    sampling_interval: 128
    requirements: duration=2 days & cuda(mem=24G)

retrieval:
    requirements: duration=2 days & cuda(mem=24G)
    topK: 1000
    retTopK: 50
    batch_size_full_retriever: 200
    negative_sampler_topk: 200
